# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002cbebb3073fec8f72c8a127df659676db949c31b312109a71e7b258547ff33c95bc29c6dba6557fc30ff6b3070a7bf7765c529836a9e87961a7469bca8cc7f

test:
  secret_key_base: 28483b5e3dec95407926f75b58845a5877bc82de96b6f868946a0b640be29f851f8e7d733f0dd8b19c63aab4e93e49f58c3287fbcef0ae63640a7e1eb5d72489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
